name: Flake check

on:
  push:
    branches: [master]
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/flake-check.yaml"
      - ".github/actions/setup-nix/**"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/flake-check.yaml"
      - ".github/actions/setup-nix/**"

permissions:
  contents: read

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: ./.github/actions/setup-nix
        with:
          cache-key: flake-check

      - name: nix flake check
        run: nix flake check --all-systems --no-build
